### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by gentlecoder** [Viijay-Kr/react-ts-css#107]
- Issue Type: `Performance`
- Extension Name: `react-ts-css`
- Extension Version: `2.3.0`
- OS Version: `Darwin x64 22.1.0`
- VS Code version: `1.81.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/3f/z8mscz_x22vbgmwrjlpr8vgc0000gn/T/viijay-kr.react-ts-css-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Viijay-Kr** [comment]
@gentlecoder could you turn of cssReferences and codeLens settings and check the load again ? just want to know if the high load is caused by something else besides those to features

**Comment by Viijay-Kr** [comment]
@gentlecoder Thanks for reporting . I did some investigation and definitely the CSS Codelens and References feature is responsible for this high load.

I will disable these two features in the follow up release. In the meantime please feel free to disable these two features under the settings 
```json
  {
     "reactTsCSS.references": false,
     "reactTsCSS.codelens":false
  }
```
