### ISSUE TITLE
Suggest to classes

### ISSUE THREAD

**Issue by myagizmaktav** [Viijay-Kr/react-ts-css#110]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/Viijay-Kr/react-ts-css/assets/115627863/d30495b6-2000-4b72-9c9f-a46d80e14ac4)
In there should be suggest to container(class name) .

**Comment by Viijay-Kr** [comment]
@myagizmaktav I am not sure if I got your idea. Could you elaborate a little bit more about your request. Thanks

**Comment by myagizmaktav** [comment]
in vscode module.css class names not showing on the suggestion dropdown.
can you fix that issue pls.

**Comment by Viijay-Kr** [comment]
@myagizmaktav is this by any change related to rename issue #111  you created ? Does this happen when you rename the file and then try to get suggestions ?

If yes , this should be fixed by #112
