### ISSUE TITLE
After file renamed then not module found.

### ISSUE THREAD

**Issue by myagizmaktav** [Viijay-Kr/react-ts-css#111]
When file renamed to module.css instead .ts then go to other .tsx file then try to import module.css file giving module not found error.

**Comment by Viijay-Kr** [comment]
@myagizmaktav Thanks for reporting . This is a related to #109

**Comment by Viijay-Kr** [comment]
@myagizmaktav This is not related to #109 this could be a sync issue. I will check this one while I investigate #109
