### ISSUE TITLE
Missing support for `.parent { &__child {...} }`

### ISSUE THREAD

**Issue by JohanMouchet** [Viijay-Kr/react-ts-css#115]
The extension isn't able to resolve SCSS selectors composed with suffix selectors starting with `&__`, which is commonly used by BEM.

**To Reproduce**
1. Create a SCSS Modules file: `styles.module.scss`
2. Write the following selector
```
.parent {
  &__child {
  color: blue;  
  }
}
```
3. Import the SCSS Modules file in a React file: `import styles from "./styles.module.scss";`
4. Add the selector to an element
```
<div className={styles["parent__child"]} />
```

**Expected behavior**
The extension shows
```
Selector 'parent__child' does not exist in "./styles.module.scss"
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Additional context**
Is it a matter of adding a parser in the [utils](https://github.com/Viijay-Kr/react-ts-css/blob/main/src/parser/utils.ts#L64)?

This is a great extension, keep up the great work ✌️

**Comment by Viijay-Kr** [comment]
@JohanMouchet Thanks for opening up this issue. Yes it is indeed a matter of tweaking the `isSuffix` regex matcher . 

Feel free to open a PR if you can. 

And thanks for your feedback . If you like the extension feedback in marketplace would go a long way :)

**Comment by fundevstuff** [comment]
@Viijay-Kr I added a PR for this that seems to be working for me.

Thanks for a great extension!

**Comment by Viijay-Kr** [comment]
@JohanMouchet if this is solved Please feel free to close this one. Thanks
