### ISSUE TITLE
Errors in `.mdx` files with `mdx.checkMdx` in `tsconfig.json` appear at end of file

### ISSUE THREAD

**Issue by karlhorky** [Viijay-Kr/react-ts-css#160]
Companion issue to https://github.com/mdx-js/mdx-analyzer/issues/451

**Describe the bug**

Usage with [`unifiedjs.vscode-mdx@1.8.9`](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx) along with `viijay-kr.react-ts-css@3.2.0` leads to:

1. All errors in `.mdx` files reported at end of file
2. Selecting the IntelliSense auto-import entry for `ZoomImage` adds the new import to the bottom of the code

Disabling `viijay-kr.react-ts-css@3.2.0` leads to errors being reported in the correct locations

**To Reproduce**

1. Clone the reproduction at https://github.com/karlhorky/repro-mdx-analyzer-missing-auto-import-intellisense
2. Install the `package.json` dependencies
3. Install the 2 recommended extensions `unifiedjs.vscode-mdx@1.8.9` and `viijay-kr.react-ts-css@3.2.0` (both enabled)
4. In `app/message.mdx`, observe that the errors are reported at a one-character red squiggly at the end of the file, instead of in the correct locations

![Screenshot 2024-06-28 at 19 27 42](https://github.com/Viijay-Kr/react-ts-css/assets/1935696/d953e069-b6dd-42d2-8f27-1279b85c8259)

https://github.com/Viijay-Kr/react-ts-css/assets/1935696/6dc9d71b-7d75-4615-ba53-4a027eae83fc

**Expected behavior**

1. Error reported in correct location
2. Selecting the IntelliSense auto-import entry for `ZoomImage` should add the new import to the top of the code 

**Screenshots**

Already included above

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Sonoma 14.5 (23F79)

VS Code version information:

```
Version: 1.91.0-insider
Commit: aea213b7fcc7de5c24ad797ac1af209b159d451f
Date: 2024-06-28T06:02:58.030Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

**Additional context**

--

**Comment by Viijay-Kr** [comment]
Seems interesting. Initial thoughts. 1.The extension should not be activated for MDX language unless they are considered as JSX (courtesy MDX extension)
2. Do yo see any error on hover ?

**Comment by karlhorky** [comment]
> 1.The extension should not be activated for MDX language unless they are considered as JSX (courtesy MDX extension)

Good to know, maybe that's useful information for tracking down this problem.

> 2. Do yo see any error on hover ?

Yes, it's visible in the video

**Comment by Viijay-Kr** [comment]
@karlhorky Did you notice this , ? the extension never gets activated like I presumed

<img width="969" alt="Screenshot 2024-06-30 at 16 22 54" src="https://github.com/Viijay-Kr/react-ts-css/assets/8697234/09c99d7e-282a-4446-8f58-3ba8afbc8ece">

**Comment by Viijay-Kr** [comment]
@karlhorky I modified the langauge service plugin based on the volar PR 

https://github.com/Viijay-Kr/typescript-cleanup-defs/pull/4 .

This fixes the problem for me . I tested it locally . If you wish to test it ? clone the repo , link the package in react-ts-css project and run the extension locally , the errors appear at the right location

**Comment by karlhorky** [comment]
With "the Volar PR", you mean https://github.com/volarjs/volar.js/pull/216, right? I wonder if this PR will actually resolve the issue, once it is pulled in to MDX Analyzer and a new version of MDX Analyzer released...

**Comment by Viijay-Kr** [comment]
> I wonder if this PR will actually resolve the issue, once it is pulled in to MDX Analyzer and a new version of MDX Analyzer released...

I don't follow this 🤔. I haven't gone over mdx analyzer project. Does MDX analyzer process all the typrescript server plugins installed by other extensions ? even if it did I tested it using the setup you recommended , using the mdx analyzer extension. So please enlighten me If I am missing something   

> With "the Volar PR", you mean [volarjs/volar.js#216](https://github.com/volarjs/volar.js/pull/216), right?

Yes thats right.

**Comment by karlhorky** [comment]
> I tested it locally . If you wish to test it ? clone the repo , link the package in react-ts-css project and run the extension locally , the errors appear at the right location

I would try to test this out today - just having trouble understanding the instructions.

Is there a way to apply the patch manually (eg. from [the Files changed in the PR](https://github.com/Viijay-Kr/typescript-cleanup-defs/pull/4/files)) by editing the extension files locally on my machine? (instead of building/linking anything or installing a different local version of the extension) Something similar to the workflow of editing `node_modules` by hand?

**Comment by karlhorky** [comment]
Ah yeah, I can edit the files in place by editing this file:

```
code ~/.vscode/extensions/viijay-kr.react-ts-css-3.2.0/node_modules/typescript-cleanup-definitions/index.js
```

This was the change I applied:

```diff
-            const proxy = Object.create(null);
+            const proxy = new Proxy(info.languageService, {
+                get(target, p, receiver) {
+                    return Reflect.get(target, p, receiver)
+                },
+                set(target, p, newValue, receiver) {
+                    return Reflect.set(target, p, newValue, receiver)
+                },
+            });
```

This indeed resolves the problem:

**Before**

![Screenshot 2024-07-07 at 17 23 45](https://github.com/Viijay-Kr/react-ts-css/assets/1935696/621c024c-4432-44c6-a48c-1d4a3252f2e4)


**After**

![Screenshot 2024-07-07 at 17 23 25](https://github.com/Viijay-Kr/react-ts-css/assets/1935696/1ad3948d-a0ea-47bc-9b18-01c51a047e2d)

**Comment by karlhorky** [comment]
Hm, I just noticed new behavior which appears to be caused by [`viijay-kr.react-ts-css@3.2.1`](https://github.com/Viijay-Kr/react-ts-css/releases/tag/v3.2.1):

- <kbd>cmd</kbd>-click no longer opens the peek view or jumps to definitions (also in TypeScript files)

Does the same happen for you @Viijay-Kr ?

**Comment by Viijay-Kr** [comment]
@karlhorky The upstream issue https://github.com/mdx-js/mdx-analyzer/issues/451 has been closed . So having the latest version of mdx analyzer and react css modules does not solve the problem in this extension ?

**Comment by karlhorky** [comment]
Copying [my comment](https://github.com/mdx-js/mdx-analyzer/issues/451#issuecomment-2298237964) here for visibility:

The problem is half fixed: I tried out the new version with [the reproduction repo](https://github.com/karlhorky/repro-mdx-analyzer-missing-auto-import-intellisense) from [the original issue description](https://github.com/mdx-js/mdx-analyzer/issues/451#issue-2378768575) and:

1. Correct error locations are used with the (deprecated) Styled Components VS Code extension
2. Incorrect error locations (end of file) still appear with the React CSS modules VS Code extension (related issue: https://github.com/Viijay-Kr/react-ts-css/issues/160)

https://github.com/user-attachments/assets/ab2edde5-1827-40f7-9f74-606eb4a8cc48

**Comment by Viijay-Kr** [comment]
@karlhorky Check this out 
https://github.com/Viijay-Kr/typescript-cleanup-defs/pull/5

I have adapted the changes similar to volar. Turns out in previous MR , I did not do the changes as intended. A bit premature .  

I tested this one so prior definitions work as expected. So it should be a potential fix

**Comment by karlhorky** [comment]
@Viijay-Kr thanks for the publish of `viijay-kr.react-ts-css@3.2.4`, I can confirm the MDX errors are in the correct positions again! 🎉


https://github.com/user-attachments/assets/2e204850-b517-4873-962a-a65dafcf2ff4
