### ISSUE TITLE
Support for classes within CSS `:not()` selectors

### ISSUE THREAD

**Issue by thykka** [Viijay-Kr/react-ts-css#173]
Say I have a rule that only applies when a specific classname is not present:

```scss
.foo {
  /* ... */
  &:not(.active) {
    opacity: 0.5;
  }
}
```

```tsx
import classNames from "classnames";
import styles from "./Foo.module.scss";

export const Foo = ({ isActive }: { isActive: boolean }) => {
  return (
    <div
      className={classNames({
        [styles.foo]: true,
        [styles.active]: isActive,
      })}
    >
      foo
    </div>
  );
};
```

Functionally, this works. We get the expected classname when `isActive` is true, and the corresponding styles are applied when it's not:

<img width="392" alt="image" src="https://github.com/user-attachments/assets/e77b7959-dfb2-47cd-8109-b31b70ef9f8b">

But in VS Code, we get a squiggly warning:

<img width="964" alt="image" src="https://github.com/user-attachments/assets/b0ea1372-aa1c-4ddd-8cc2-e1a3b6ae7ec9" title="`Selector 'myclass' does not exist in 'file.module.scss'. Add this selector to file.module.scss`">

Would be nice if we didn't have to ignore these warnings with comment directives?

**Comment by Viijay-Kr** [comment]
@thykka Thanks for reporting the issue. You are absolutely right , the support for pseudo class functions should have been there. 

I opened a MR to fix this 🤞🏼
