### ISSUE TITLE
VS Code Auto-Import for `styles` default export from `*.module.css/scss/sass`

### ISSUE THREAD

**Issue by karlhorky** [Viijay-Kr/react-ts-css#20]
Hi @Viijay-Kr! 👋

Would you consider allowing auto-import for the `styles` default export from `*.module.css`, `*.module.scss` and `*.module.sass` files?

Similar to the feature implemented in https://github.com/apptools-lab/appworks/pull/961 for the [**React Style Helper** extension](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks-style-helper):

![136906513-bae3f12e-be97-4e0b-b223-95daa248b03f](https://user-images.githubusercontent.com/1935696/211012205-42436e8d-0832-4fa5-9da2-f6448510a4a2.gif)

**Comment by Viijay-Kr** [comment]
@karlhorky Thanks for reporting this 

IMO This is a good to have feature.
Although the scope of this extension is to give you information about selectors based on css/scss modules and I would consider this feature to be trivial considering the arbitrary nature of the css modules you could have in your project.

**Comment by Viijay-Kr** [comment]
@karlhorky A Basic version of this feature is published in 1.3.2 

Let me know how it works. 

Unlike [React Style Helper extension](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks-style-helper):

React TS CSS would give suggestions of various css modules in your workspace. On selection the module will be imported automatically.

Some improvements I already noted down
1. On selection the auto import is not so obvious.
2. The path of the imported module is currently absolute. Some improvements could be done here based on tsconfig settings

**Comment by Viijay-Kr** [comment]
@karlhorky I went a little ambitious on this one. 

Looks like your suggestions are very much valuable 

> maybe it should be filtered to the current directory (or current directory + parent directory + grandparent directory)?

This alone would solve many issues.
 For the first version I can ship the support only in the current directory.

I tried React Style helper , the auto import along with auto complete  never works for me. 
Also some times auto complete wont work inside `className={}`.

**Comment by Viijay-Kr** [comment]
https://github.com/Viijay-Kr/react-ts-css/issues/20#issuecomment-1379995583

This has been shipped .

Closing this thread . If anything a new thread can be opened :)

**Comment by karlhorky** [comment]
This is working well with `v1.3.5` 🙌  Nice work, thanks so much!

Going to remove the [**React Style Helper** extension](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks-style-helper) from the student instructions and switch completely over here!

**Comment by Viijay-Kr** [comment]
@karlhorky 

Thanks a lot for the feedback . 

I would be so pleased if you could participate in a small survey 

https://forms.gle/rcGxv2hUbwU4rRX18
It has only three questions .
Please feel free to pass on to your students as well.

Thanks

**Comment by karlhorky** [comment]
Great, filled the survey out, hope my feedback is useful for you! I also wrote a review for the extension on the VS Code extension marketplace: https://marketplace.visualstudio.com/items?itemName=viijay-kr.react-ts-css&ssr=false#review-details

**Comment by Viijay-Kr** [comment]
Thanks a lot @karlhorky
