### ISSUE TITLE
CSS variables does not auto complete from variable file - Next JS

### ISSUE THREAD

**Issue by Viijay-Kr** [Viijay-Kr/react-ts-css#67]
@karlhorky Can you add more details to this one ?

I can't reproduce this

**Comment by karlhorky** [comment]
Does the extension read all variables from all `.css` / `.scss` / `.sass` files across the whole project?

I am getting it to work with `*.module.css` files but not with `*.module.scss` files.

Maybe what I'm actually asking for is #63 ?

**Comment by Viijay-Kr** [comment]
You are right , the css language features only support css for now until #63 is figured out

**Comment by Viijay-Kr** [comment]
@karlhorky Aren't yo using [Scss Intelli](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss).

This extension covers variable level intellisense across various sass files.

**Comment by karlhorky** [comment]
> Aren't yo using [Scss Intelli](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss).
> 
> This extension covers variable level intellisense across various sass files.

Right now I'm using [the CSS Variable Autocomplete extension](https://marketplace.visualstudio.com/items?itemName=vunguyentuan.vscode-css-variables), which also supports SCSS. But if we can use your extension instead for all features, then I would want to do that. The fewer extensions that we need to have installed, the better.

**Comment by karlhorky** [comment]
> You are right , the css language features only support css for now until #63 is figured out

Ok sounds good, then I'll close this one and we'll track this in #63

**Comment by Viijay-Kr** [comment]
> 

makes sense

> > Aren't yo using [Scss Intelli](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss).
> > This extension covers variable level intellisense across various sass files.
> 
> Right now I'm using [the CSS Variable Autocomplete extension](https://marketplace.visualstudio.com/items?itemName=vunguyentuan.vscode-css-variables), which also supports SCSS. But if we can use your extension instead for all features, then I would want to do that. The fewer extensions that we need to have installed, the better.
