### ISSUE TITLE
Feature Set v2.0.0

### ISSUE THREAD

**Issue by Viijay-Kr** [Viijay-Kr/react-ts-css#8]
- [ ] **Refactor Symbol**
- [ ] **Reference provider**
- [ ] **Plain Selectors support**
    - [ ] **No Module identifier**
- [x] **Symbol Not found warning**
- [ ] **Dynamic selectors**
- [ ] **Compile Sass Code blocks for peek**

**Comment by karlhorky** [comment]
Maybe the auto-import feature would also be a candidate for a feature for 2.0.0?

- #20
