### ISSUE TITLE
Classes with suffixes added via SCSS parent selector aren't picked up by the extension

### ISSUE THREAD

**Issue by figurae** [Viijay-Kr/react-ts-css#82]
**Description**
Classes with suffixes added via SCSS parent selector aren't picked up by the extension

**Steps to reproduce the behavior:**
fresh VSCode with just React CSS modules installed

1. `npx create-react-app@latest . --template typescript`
2. `npm i sass`
3. `mv src/App.css src/App.module.scss`
4. replace `import './App.css';` with `import styles from './App.module.scss';` in `App.tsx`
5. place `declare module '*.module.scss';` in scss.d.ts
6. change class names in `App.tsx` to styles.name and styles['dashed-name'] format
7. add a new class containing a parent selector adding a suffix
8. use both classes in the tsx
9. see error on suffixed class, it is neither previewed on hover nor autocompleted

**Expected behavior**
The suffixed class should be picked up by the extension.

**Screenshots**
![react-ts-css-issue](https://user-images.githubusercontent.com/89541173/218331979-07beb20c-c095-4c92-9da4-924f64a084b7.jpg)
![react-ts-css-issue-2](https://user-images.githubusercontent.com/89541173/218331985-692419db-923a-41c0-bd10-8b9d70d6dc28.jpg)

**Desktop**
- OS: Windows 10 21H2 and latest Manjaro Linux
- VSCode 1.75.1

**Additional context**
I've also seen some minor grievances (the hover preview and error messages only update on file save, new classes in the SCSS module aren't picked up until Code is restarted), but this one is critical to me. Maybe I'm missing some obvious thing I'm supposed to do here (I've recently started learning React), but I haven't been able to find a solution. I've also tried React Style Helper and it works fine for suffixed classes but doesn't provide any error message for invalid class names at all, so I'd rather use this extension.

**Comment by Viijay-Kr** [comment]
@figurae Thanks for opening this issue. 

The extension currently  account for selectors that are defined inside a parent which starts with `&-` prefix.

So this use case is not accounted for yet . That said , it should be an easy fix.

**Comment by Viijay-Kr** [comment]
> I've also seen some minor grievances (the hover preview and error messages only update on file save, new classes in the SCSS module aren't picked up until Code is restarted), but this one is critical to me

could you open a issue regarding these glitches you have

**Comment by Viijay-Kr** [comment]
@figurae this issue should be fixed after you install 1.9.1

**Comment by Viijay-Kr** [comment]
> I've also seen some minor grievances (the hover preview and error messages only update on file save, new classes in the SCSS module aren't picked up until Code is restarted)

@figurae I too noticed this problem in my projects . This has been fixed since 1.9.2
