### ISSUE TITLE
Support dynamic access of CSS module classes

### ISSUE THREAD

**Issue by strlns** [Viijay-Kr/react-ts-css#86]
**Is your feature request related to a problem? Please describe.**
Admittedly this is an edge case and probably hard to implement, but if I do something like
```
classNames[size]
```
, VSCode flags it as a "problem":
> Selector 'size' does not exist in 'src/styles/Container.module.css'.

**Describe the solution you'd like**
*Ideal solution:*

Probably you'd need to use VSCode's TypeScript language server to try and statically analyze if the given
string corresponds to a valid selector. This might be overly expensive or hard to implement, I'm not sure.

*Pragmatic solution*
Detect dynamic property access and print a different or no warning in this case. Also, the warning seems to assume `size` is used as a literal property name in my example, which it definitely is not.

Differentiating dynamic and static access would allow me to disable the warning for dynamic property access, but still benefit from the warning for a static selector. 

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/4463870/222177930-0a58d109-2428-4b44-95ed-a65da7ce17bc.png)

**Comment by Viijay-Kr** [comment]
@strlns Thanks for opening the issue. 

I do like your ideas , 

> Probably you'd need to use VSCode's TypeScript language server to try and statically analyze if the given
string corresponds to a valid selector. This might be overly expensive or hard to implement, I'm not sure.

This could be achieved through a typescript server plugin by intercepting the editor actions such as hover and definition.
However it might be expensive to implement.

> Detect dynamic property access and print a different or no warning in this case. Also, the warning seems to assume size is used as a literal property name in my example, which it definitely is not.

This might be a littler easier to compute thus requiring less effort. I will try to resolve this sooner in the meantime if you'd like to contribute feel free to open a PR

**Comment by Viijay-Kr** [comment]
@strlns 

> Detect dynamic property access and print a different or no warning in this case. Also, the warning seems to assume size is used as a literal property name in my example, which it definitely is not.

This turned to be quite easy to plug in. So it should be fixed by #87 

In the future it might be possible to provided some nice solution to the first idea you presented. 

I can open a new issue by listing out various possible actions that can happen applied to dynamic selectors

**Comment by strlns** [comment]
Nice"
I have not contributed to VSCode extensions before but will look at your fix and extension code for learning a bit about extension development.
Thank you for your swift reaction!
Moritz

**Comment by Viijay-Kr** [comment]
@strlns I opened a new issue #88 where I've brainstormed a bit . feel free to join that thread to provide your input.

Again, thanks for opening this issue
