### ISSUE TITLE
Support for tsconfig paths in monorepo

### ISSUE THREAD

**Issue by alexng353** [Viijay-Kr/react-ts-css#97]
**Is your feature request related to a problem? Please describe.**
Quite frustrated with module resolution using `@aliases` in a nextjs app with this monorepo structure:
```
/
	/apps
		/web
		/api
		...
```

I tried a lot of things with the settings, changing the tsconfig resolution, changing the base directory, etc etc. I can't seem to figure out how on earth to get it to resolve properly.

**Describe the solution you'd like**
Either a solution on how to get this to actually work properly in the extension, or, if it doesn't work at all, having it work properly.

**Describe alternatives you've considered**
I've tried disabling the diagnostics but that removes too many features.

**Additional context**
I've only been trying this for a few hours, but it's been taking a lot of my time up recently so I'm just going to give up for the time being.

**Comment by Viijay-Kr** [comment]
@alexng353 I'm sorry to hear about your frustration. Can you provide me with a reproducible example repo that I can check

**Comment by Viijay-Kr** [comment]
@alexng353 Feel free to try out #99 locally if you can .  I have covered scenarios with tsconfig aliases in a mono repo and poly repo setup.
