### ISSUE TITLE
Publish on Open VSX

### ISSUE THREAD

**Issue by quazar-omega** [Viijay-Kr/react-ts-css#98]
Could you add the extension to [Open VSX](https://open-vsx.org/) as well please?  
It will make it easier for us that use other non-Microsoft builds of VSCode like VSCodium to install and update the extension.

Some links:
- [About Open VSX](https://open-vsx.org/about)
- Who's using it? <sup>[source](https://www.globenewswire.com/news-release/2023/06/27/2695137/0/en/The-Open-VSX-Registry-a-Vendor-Neutral-Community-Supported-Alternative-to-the-Visual-Studio-Marketplace-Gets-its-Own-Working-Group-at-the-Eclipse-Foundation.html)</sup>
  > As an open alternative to the Visual Studio Marketplace, the Open VSX Registry offers free access to extensions that can be used with any technology or tool that supports them. These include many open source solutions like **Eclipse Che and Eclipse Theia, as well as Salesforce Code Builder, Google Cloud Workstations, Gitpod, SAP Business Application Studio and other applications based on Eclipse projects**.
- [How to publish](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

**Comment by Viijay-Kr** [comment]
@quazar-omega This sounds interesting. I will go through the links you have provided and get back to you.

**Comment by Viijay-Kr** [comment]
@quazar-omega The extension is available in Open VSX under 

https://open-vsx.org/extension/viijay-kr/react-ts-css

**Comment by quazar-omega** [comment]
Thank you, that was super quick!
